[server]
	host = "192.168.31.67"
	#host = "127.0.0.1"
	port = 2323
	base_dir = "res"

[core]
	handle_threads = 2
	listen_que = 10
	max_events = 1000

[logger]
	async = true
	#log_file = "http_server.log"

[http]
	max_header_size = 4096 	#最大头部总大小
	max_header_fields = 100 #最大头部字段个数
